### ISSUE TITLE
Recaf

### ISSUE THREAD

**Issue by brunoffsp** [romainbutteaud/Kaffeine#12]
I wasn't sure if the six hour scheduler was working for me, so I took a decaf and went to caf again. But now a red "something went wrong" message is showing up. The website counter decremented after my decaf, so the app is not caf anymore.

**Comment by michaelryu** [comment]
Having the same problem myself.

**Comment by jinpark** [comment]
Looks like there was a problem with the bedtime PR. Returning a 500 on `http://kaffeine.herokuapp.com/register `

**Comment by romainbutteaud** [comment]
@brunoffsp @michaelryu @jinpark now should be good, please try again.

**Comment by jinpark** [comment]
Works for me! Thanks!

**Comment by brunoffsp** [comment]
Solved here too.

**Comment by brunoffsp** [comment]
Thanks!
