### ISSUE TITLE
Bedtime input hides am/pm on chrome

### ISSUE THREAD

**Issue by jinpark** [romainbutteaud/Kaffeine#13]
Currently on latest chrome/mac it looks like

![image](https://cloud.githubusercontent.com/assets/1847812/9379601/74fcdad4-4765-11e5-8817-e26b6befb0f1.png)

which is a bit confusing if youre trying to select AM/PM

If you remove the width on the input element (which is hardcoded at 70px), you can see AM/PM

![image](https://cloud.githubusercontent.com/assets/1847812/9379621/8a49bf2e-4765-11e5-9bdd-5aa4ed5279f6.png)

**Comment by romainbutteaud** [comment]
Verify?

**Comment by jinpark** [comment]
Looks good now! Thanks for the quick turnaround
