### ISSUE TITLE
Internal Server Error when trying to add an app to the site 

### ISSUE THREAD

**Issue by DannyDainton** [romainbutteaud/Kaffeine#17]
Each time I try and add my app "releasenotesfinder" to the site it throws a 500 error in the browser console.

![server_error](https://cloud.githubusercontent.com/assets/17089546/19938036/78d175be-a11b-11e6-9066-950336f453ee.png)

**Comment by druminski** [comment]
I have the same error

**Comment by HeroCC** [comment]
Same here

**Comment by akshaybharwani** [comment]
Still happening.

**Comment by tejashah88** [comment]
The error appears to be here.

![image](https://cloud.githubusercontent.com/assets/11187343/21472965/c89abf9c-caa6-11e6-894f-73270b58a523.png)

The buggy file seems to be located here: http://kaffeine.herokuapp.com/assets/application-c5ce772b17faefa483b7882ebdf10f8e.js:formatted

**Comment by shanebrunette** [comment]
same error..

**Comment by dallaswmorgan** [comment]
same error still persisting

**Comment by IvanVas** [comment]
Confirmed. Still a problem

**Comment by bergben** [comment]
Hey guys, doesn't look like Kaffeine is under active support / development anymore. I did some googling and found this alternative http://wakemydyno.com. I hope it helps some of you

**Comment by romainbutteaud** [comment]
Sorry guys, I looks like the Heroku revoked DB write access since Kaffeine's DB table is above 10K rows. 

> 10,234 of 10,000 ROWSWRITE ACCESS REVOKED

**Comment by dideler** [comment]
Hey @romainbutteaud, great service!

One option that would free up some space and keep costs low for you (by not bumping your pg plan) would be to auto-remove any apps that 404. I could work on a PR for this if you think it's a good idea.

**Comment by andrysds** [comment]
😢 is kaffeine still down for new app?

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.

**Comment by romainbutteaud** [comment]
@dideler that's a great idea! feel free to submit a PR!
