### ISSUE TITLE
Service does not support custom domain

### ISSUE THREAD

**Issue by itsmingjie** [romainbutteaud/Kaffeine#18]
This service does not support custom domain.
When you add custom domain to heroku, it removes the http://app-name.herokuapp.com domain. So there is no way I can add my app to this service any more.

Can you remove the restrictions of the domain so that not only Heroku, other PaaS like OpenShift can be benefited, too?

Thanks.

**Comment by romainbutteaud** [comment]
@itsmingjie that's a good idea - feel free to submit a PR if you have time.

**Comment by ruslankurmanaleev** [comment]
> This service does not support custom domain.
> When you add custom domain to heroku, it removes the http://app-name.herokuapp.com domain. So there is no way I can add my app to this service any more.
> 
> Can you remove the restrictions of the domain so that not only Heroku, other PaaS like OpenShift can be benefited, too?
> 
> Thanks.

You're wrong. You ALWAYS have a herokuapp. domain active until you remove an app or rename it.
Recently I changed customs domains a lot, that's why the mobile-traffic (API) comes directly to herokuapp.com as I'm tired of updating the android app just because of domain's name.

**Comment by itsmingjie** [comment]
Jesus man it's been 3 years since that issue a lot has changed :man_shrugging: Closing now
