### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jonchoi** [romainbutteaud/Kaffeine#19]
Getting an error

![image](https://cloud.githubusercontent.com/assets/9872658/25094736/6d5095e4-234d-11e7-80b7-0762ea189a3b.png)

**Comment by cmdalbem** [comment]
same here :/

![image](https://cloud.githubusercontent.com/assets/467471/25116111/12f16986-23e1-11e7-843c-927ed5ae1c1a.png)

**Comment by gswalden** [comment]
see https://github.com/romainbutteaud/Kaffeine/issues/17#issuecomment-282066033

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.
