### ISSUE TITLE
Just set up for my Heroku app, but Kaffeine does not seem to be keeping it awake

### ISSUE THREAD

**Issue by deborah-ufw** [romainbutteaud/Kaffeine#21]
Hi, I set up app "multi-wing-flyer" but it does not seem to be staying awake. I am in California and set sleep time to GMT 6:00 a.m., which should make the "sleep" window from Midnight to 6:00 a.m. California time.

Is Kaffeine definitely still operating?

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.
