### ISSUE TITLE
Something went wrong message on Kaffeine

### ISSUE THREAD

**Issue by FarahYQ** [romainbutteaud/Kaffeine#22]
Hi,
I've been trying to put my app (https://liftoff-go.herokuapp.com/#/) on Kaffeine, but it keeps saying "Something went wrong". I'm not sure what is going wrong though. Could you check to see if you know what the issue is? As far as I can tell, all my Heroku settings are the same as other apps that are working with Kaffeine.

Thank you for your help!
Farah

**Comment by DespertaWeb** [comment]
Mine is throwing the message to: https://hommy.herokuapp.com/

**Comment by BennyEvans** [comment]
Yep, same issue here.

**Comment by RichardPK** [comment]
Ah dang, same thing here.

**Comment by alex-wood** [comment]
Any updates on this?

**Comment by ryansama** [comment]
Same here, any update?

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.
