### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by morgannewman** [romainbutteaud/Kaffeine#25]
Looks like the something went wrong error is back! I suspect the DB needs to be purged of inactive apps.

**Comment by park-bohee** [comment]
I wrote my app name and set the time. But there was an error. why??

**Comment by imhotepper** [comment]
I get the same error ;(

**Comment by RonnieOnRails** [comment]
same today

**Comment by MuhammadOvi** [comment]
Same issue 😢

**Comment by imhotepper** [comment]
Based on the records displayed it looks like the DB is full :( 
![kaffeine full](https://user-images.githubusercontent.com/176727/51627124-da79cd80-1f49-11e9-9a6f-df6c3767d55f.png)

**Comment by Hugo0** [comment]
Same issue as well.

**Comment by michaelrkn** [comment]
Same issue (commenting so I can get updates)

**Comment by bergpb** [comment]
Someone trying to contact @romainbutteaud your email returns after send and your twitter account is inaccessible.

**Comment by romainbutteaud** [comment]
yes looks like the DB is full - I can try to purge it

**Comment by bergpb** [comment]
awesome, im try add a new heroku app and works again thanks @romainbutteaud.

**Comment by writer0713** [comment]
@romainbutteaud 
DB is full again. I think.
"something is wrong" message :(

**Comment by ben0it8** [comment]
same for me!

**Comment by writer0713** [comment]
@romainbutteaud why don't u pick some contributters to see issues.
or, make an automation tool for this issue.

**Comment by chihsienyen** [comment]
get the "something is wrong" message
I'd appreciate if it can be fixed 😃

**Comment by deckerjeferson** [comment]
Hey @romainbutteaud I think that the DB is full again :/
I'm getting something went wrong :/

**Comment by sylviamoss** [comment]
same for me!

**Comment by ndstephens** [comment]
same here...bummer

**Comment by anechol** [comment]
same :(

**Comment by arielwulkan** [comment]
same for me!

**Comment by Paul3MK** [comment]
Still getting the error message

**Comment by romainbutteaud** [comment]
I took the whole app down while reseting the DB, I will need to redeploy it with the newer Ruby version. I'll try to do it this week.

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.

**Comment by joisadler** [comment]
Hello! I'm trying now to add my app and get the "something went wrong" error.
Number of users for this moment is 100645.
Is the DB full again?

**Comment by writer0713** [comment]
guys, just use below service(free).

https://cron-job.org/en/

**Comment by anechol** [comment]
> 
> 
> guys, just use below service(free).
> 
> https://cron-job.org/en/

Thanks for providing this! I've gotten around by using a basic setInterval script, but this might be useful for others.

**Comment by ra312** [comment]
The same problem
