### ISSUE TITLE
Can't "Recaf"

### ISSUE THREAD

**Issue by deckerjeferson** [romainbutteaud/Kaffeine#26]
Hello!
I've wanted to change the sleeping ours 2 of my apps. I've managed to delete them, but I try to "Kaffeine" it again, I always receive a "something went wrong" error.

**Comment by anechol** [comment]
yep getting the same error. my discord bot has been down for like two days lol

**Comment by corsojulian7** [comment]
Yes, same issue

**Comment by romainbutteaud** [comment]
I've reseted the DB because we reached the 10K DB row limit on the free Heroku DB plan. Feel free to re-add your apps.
