### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by vvorlov** [romainbutteaud/Kaffeine#29]
I am getting "Something went wrong." when trying to add my app.

**Comment by MrNocTV** [comment]
I have the same problem, checking the header I got this
`Request URL: https://kaffeine.herokuapp.com/register
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 52.206.54.179:443
Referrer Policy: strict-origin-when-cross-origin
`

It has something to do with CORS

**Comment by romainbutteaud** [comment]
@vvorlov @MrNocTV  it's back on. I did a reset of the DB.
