### ISSUE TITLE
Option to remove your app from the list

### ISSUE THREAD

**Issue by dideler** [romainbutteaud/Kaffeine#3]
If someone wants, for whatever reason, to have Kaffeine no longer ping their app.

**Comment by itnamerica** [comment]
Kaffeine pinging your app may increase the cost of your Heroku plan. It's important to have the option to remove it from the list.

**Comment by AniketAgarwal21** [comment]
I have had all my free dyno hours exhausted due to this, can you please remove my websites from your database?
