### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by Arshad-Barves** [romainbutteaud/Kaffeine#30]
I'm getting this issue on Kaffeine Can you please resolve this resolve Hurry.

**Comment by joisadler** [comment]
Hello! I'm trying now to add my app and get the "something went wrong" error.
Number of users for this moment is 100645.
Is the DB full again?

**Comment by yangrussell** [comment]
I have the same issue. Thanks!

**Comment by dalovar** [comment]
Same issue...

**Comment by borasumer** [comment]
Yeah same issue for me too.

**Comment by searchy2** [comment]
Please take a look at this issue when you get the chance. Thanks!

**Comment by JEVBR** [comment]
DB must be full at 100624 users

**Comment by LukasDeco** [comment]
It would be so wonderful if someone created a Kaffeine 2.0 or increased the amount of users available

**Comment by romainbutteaud** [comment]
@Arshad-Barves @joisadler @yangrussell @dalovar @borasumer @searchy2 @JEVBR @LukasDeco it's back on. I did a reset of the DB.
