### ISSUE TITLE
Being able to remove apps from the admin section

### ISSUE THREAD

**Issue by romainbutteaud** [romainbutteaud/Kaffeine#4]

**Comment by cameronehrlich** [comment]
Love this service! Would be cool if you could remove your app though...

**Comment by romualdr** [comment]
+1, nice work so far though ;)

**Comment by graf-abolmasov** [comment]
Great Pull Request. Looking forward when it will be merged

**Comment by olivierbuffon** [comment]
:+1:

**Comment by romainbutteaud** [comment]
@cameronehrlich, @olivierbuffon, @graf-abolmasov, @romualdr you can now remove your apps on Kaffeine: http://kaffeine.herokuapp.com/#decaf
Thanks to @acrogenesis !
