### ISSUE TITLE
#decaf doesn't open until refreshed 

### ISSUE THREAD

**Issue by AniketAgarwal21** [romainbutteaud/Kaffeine#48]
When I clicked the option to remove my app, it pointed to #decaf in the URL but the pop-up box didn't appear until I refreshed.
Please fix this as I thought there isn't any option to remove my app at first.

**Comment by jasmaa** [comment]
There seem to be some compatibility issues between CSS Modal and Turbolinks. As a quick fix, I was able to get the modal to work again by removing the Turbolinks directive below:

https://github.com/romainbutteaud/Kaffeine/blob/5bdda527ca3d71fe8be49e0acdf196bf05e7f4ed/app/assets/javascripts/application.js#L15
