### ISSUE TITLE
With new rules, how does this work?

### ISSUE THREAD

**Issue by Snorlock** [romainbutteaud/Kaffeine#9]
It seems to have come new heroku sleep rules now. It has to sleep 6 hours a day.
And if it doesnt recieve a web request within the last 30 minutes, it goes to sleep. Maybe you should knock down your time with like 5 minutes to keep within the timerange?
Not sure how to get around the 6 hours of sleep per day though.

https://devcenter.heroku.com/articles/dyno-types#dyno-sleeping

I was a littlebit fast with this, it seems that these dynos are in beta, so we will se what happens.

**Comment by kubukoz** [comment]
These changes come to life on July 1st this year, so in less than a month.
I'd really love to know if I have to migrate...
@romainbutteaud, do you have any plans on targeting this? :)

**Comment by romainbutteaud** [comment]
Hi Jakub,

I haven't had time to look at this yet. I will try to do this by next week.

Cheers,
Romain

**Comment by alexanderzeillinger** [comment]
I suggest you change the requests to happen only between 6:00 and 24:00 which should be enough for most users.

**Comment by romainbutteaud** [comment]
@alexanderzeillinger good idea. I was thinking letting the user choose himself the 6h of sleep his app (because of different Timezone, usage, ect...)

**Comment by alexanderzeillinger** [comment]
@romainbutteaud that's of course even better :-)

**Comment by NARKOZ** [comment]
Got this email from Heroku today:

>Your app *** is running on free dynos and has been active for more than 18 of the last 24 hours. Normally, your app would sleep for the next 6 hours. Don't worry, your app is still running - during the public beta we're simply sending notifications to raise awareness so you have ample time to adjust.

The title of the email is "Your Heroku app ** on free dynos needs to sleep".

**Comment by alexanderzeillinger** [comment]
@romainbutteaud so when are you implementing the required changes?

**Comment by romainbutteaud** [comment]
@alexanderzeillinger changes have been implemented, thanks to @txizzle. See https://github.com/romainbutteaud/Kaffeine/pull/11
